### ISSUE TITLE
“Method 'Create' in type 'Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors

### ISSUE THREAD

**Issue by HarlanGitHub** [zqlovejyc/EFCoreRepository#1]
下载下来的文件，修改了相应数据库链接，运行报错：
System.TypeLoadException:“Method 'Create' in type 'Pomelo.EntityFrameworkCore.MySql.Query.ExpressionVisitors.Internal.MySqlSqlTranslatingExpressionVisitorFactory
![image](https://user-images.githubusercontent.com/17823186/114662016-904bb500-9d2a-11eb-8c26-549914e0b8db.png)

**Comment by zqlovejyc** [comment]
暂时移除了mysql依赖包Pomelo.EntityFrameworkCore.MySql，改用官方的MySql.EntityFrameworkCore，这个问题是由于第三方包未实现官方的方法导致的；
